services:
  redis1:
    image: redis:7
    container_name: redis1
    ports:
      - "7001:6379"
    volumes:
      - ./redis1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis2:
    image: redis:7
    container_name: redis2
    ports:
      - "7002:6379"
    volumes:
      - ./redis2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis3:
    image: redis:7
    container_name: redis3
    ports:
      - "7003:6379"
    volumes:
      - ./redis3/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis4:
    image: redis:7
    container_name: redis4
    ports:
      - "7004:6379"
    volumes:
      - ./redis4/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis5:
    image: redis:7
    container_name: redis5
    ports:
      - "7005:6379"
    volumes:
      - ./redis5/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis6:
    image: redis:7
    container_name: redis6
    ports:
      - "7006:6379"
    volumes:
      - ./redis6/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]    